### ISSUE TITLE
Publish Roblox OAuth 2.0 Apps

### ISSUE THREAD

**Issue by torodavit** [PiratePeep/roblox-oauth2-example#1]
Hello, I register OAuth 2.0 Apps, I have iOS app and implemented this OAuth app in it. it's work perfect. I need publish it, but rejected. entry link is not correct, they sad. I don't have web page. I only have mobile app. What can I do about entry link?

**Comment by PiratePeep** [comment]
Did you try linking to your mobile app on the App Store? If you did and they still rejected it, you'll probably either need to make a website or try reaching out to a Roblox administrator on the DevForum.
